### ISSUE TITLE
浏览器不错，建议加个pac

### ISSUE THREAD

**Issue by Aunixtoyou** [free-vpn/chromium#25]
如题
这样对服务器压力也小点，

**Comment by Tiandians** [comment]
这个问题似乎可以通过Chrome插件Proxy SwitchyOmega来解决
Proxy SwitchyOmega中的“直接连接”模式应该可以越过浏览器内置的代理，我的插件出问题了，没办法证实
然后设置自动代理模式，列白名单，名单外的使用“直接连接”即可
具体设置教程网上都可以找到

**Comment by lon91ong** [comment]
@Tiandians 这个浏览器“直接连接”是直接连到VPN上的吧

**Comment by Tiandians** [comment]
@lon91ong 经过实测，我认为Proxy SwitchyOmega可以绕过Free-VPN内置的代理，并可以在此基础上连接其它服务商提供的代理服务。测试图如下：
直接连接模式：
![12_li](https://user-images.githubusercontent.com/35755846/46523600-ca65b180-c8b8-11e8-9009-3d97d6adf322.jpg)
系统代理模式：
![23](https://user-images.githubusercontent.com/35755846/46523677-1b75a580-c8b9-11e8-9c2b-e654dca0da40.png)
XX-Net（其它服务商）代理模式：
![24](https://user-images.githubusercontent.com/35755846/46523836-7effd300-c8b9-11e8-9ae1-f1eaac428fc7.png)

**Comment by SkyGrass** [comment]
Proxy SwitchyOmega 
可以的，测试完毕。

**Comment by jake2003a** [comment]
@Tiandians 这个浏览器Chromium不支持IDM下载东西，请问有什么办法吗？idm不能添加这个浏览器的集成。
